version: '3'

services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python wait-for-db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - mysql-fastapi 

  mysql-fastapi:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: fastapi_blog
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
