version: '3'

services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql-fastapi
  
  mysql-fastapi:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: fastapi_blog
      # MYSQL_USER: fastapi
      # MYSQL_PASSWORD: fastapi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    
